---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.88, CPAN::Meta::Converter version 2.132830'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Inline
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dumper: 2.09
  Digest::MD5: 2.09
  File::Spec: 0.8
  Parse::RecDescent: 1.8
  Test::Warn: 0.23
version: 0.54_02
